config/routes.rb
TrafficLights::Application.routes.draw do
  
  put "junctions/:id", to: "junctions#rotate", as: :rotate_junction
  put "junctions", to: "junctions#rotateall", as: :rotate_all_junctions
  resources :traffic_lights
  resources :junctions

  root "welcome#index"
  get "traffic_lights/new"
  

end

app/models/junction.rb
class Junction < ActiveRecord::Base
  has_many :traffic_lights, dependent: :destroy
  validates :name, :presence => true

  def rotate!
    self.traffic_lights.each do |traffic_light|
      traffic_light.next!
      traffic_light.save
    end
  end
end

app/models/traffic_light.rb
class TrafficLight < ActiveRecord::Base
  belongs_to :junction

  validates :junction_id, :presence => true

  @@values = ["Red", "Yellow", "Green"]
  
  def next!
    self.colour = next_colour
  end

  public
  def values
    @@values
  end

  private

  def next_colour

    if colour == @@values.last
      @@values.first
    else
      @@values[@@values.index(colour) + 1]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/junctions_controller.rb
class JunctionsController < ApplicationController


  def create
    @junction = Junction.new(junction_params)
    if @junction.save
      redirect_to @junction
    else
      render action: :new
    end

  end

  def show
    @junction = Junction.find(params[:id])
  end

  def edit
    @junction = Junction.find(params[:id])
  end

  def update
    @junction = Junction.find(params[:id])
    if @junction.update(junction_params)
      redirect_to @junction
    else
      render action: :edit
    end
  end

  def destroy
    @junction = Junction.find(params[:id])
    @junction.destroy
    redirect_to junctions_path
  end

  def rotate
    @junction = Junction.find(params[:id])
    @junction.rotate!
    redirect_to junctions_path
  end

  def rotateall
    Junction.all.each do |junction|
      junction.rotate!
    end
    redirect_to junctions_path
  end

  private
    def junction_params
      params.require(:junction).permit(:name)
    end
end

app/controllers/traffic_lights_controller.rb
class TrafficLightsController < ApplicationController

  before_filter :find_traffic_light, :except => :create
  
  def new
    if @traffic_light
        @errors = @traffic_light.errors.full_messages
    end
  end

  def create
    @traffic_light = TrafficLight.new(traffic_light_params) # create a new instance variable, which is a TrafficLight object with the parameters that we just received from the html POST
    if @traffic_light.save  # if its able to save the traffic light then show it
      redirect_to junctions_path
    else  # else go back to the 'create new' screen
      render :action => :new
    end
  end

  def edit  # new is to edit as create is to update
    @traffic_light = TrafficLight.find(params[:id]) 
  end

  def update  # that is, new and edit open the page to allow you to enter values, while create and update send those values to the database
    @traffic_light = TrafficLight.find(params[:id])
    if @traffic_light.update(params[:traffic_light].permit(:junction_id, :colour))
      redirect_to @traffic_light
    else
      render :action => :edit
    end
  end

  def destroy
    TrafficLight.find(params[:id]).destroy
    redirect_to @traffic_light
  end

  def show
    @traffic_light = TrafficLight.find(params[:id]) # pulls a traffic light back out of the database based on the ID which is still in the POST parameters
  end

  def index
    @traffic_lights = TrafficLight.all
  end


  private

    def traffic_light_params
      params.require(:traffic_light).permit(:junction_id, :colour)
    end

    def find_traffic_light
      @traffic_light = TrafficLight.new()
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/junction_helper.rb
module JunctionHelper
end

app/helpers/traffic_light_helper.rb
module TrafficLightHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/junctions/edit.html.erb
<h1>Editing junction:</h1>

<%= form_for :junction, url: junction_path(params[:id]), method: :patch do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
    <%= if @junction; @junction.errors.full_messages end %>
  </p>
  <p>
    <%= f.label :ID %><br />
    <%= params[:id] %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to junctions", junctions_path %>

app/views/junctions/index.html.erb
<style = "text/css">
  td { padding: 5px; }
</style>

<script type = "text/javascript">
 setInterval(function () {document.getElementById("rotateAll").click();}, 1000);
</script>

<h1>Junctions</h1>

<p>
  <%= link_to "New junction", new_junction_path %>
</p>

<p>
  <%= link_to "Rotate all junctions", rotate_all_junctions_path, method: :put, :id => "rotateAll" %>
</p>

<table>
  <tr>
    <td><b>Name</b></td>
    <td><b>ID</b></td>
  </tr>
  <% Junction.all.each do |junction| %>
    <tr>
      <td><%= junction.name %></td>
      <td><%= junction.id %></td>
      <td><%= link_to "Update", edit_junction_path(junction.id) %></td>
      <td><%= link_to "Delete", junction_path(junction.id), method: :delete %></td>
      <td><%= link_to "New light", new_traffic_light_path(junction_id: junction.id) %></td>
      <td><%= link_to "Rotate", rotate_junction_path(junction.id), method: :put %></td>
      <%# junction.traffic_lights.each do |traffic_light| %>
      <% TrafficLight.where("junction_id = ?", junction.id).each do |traffic_light| %>
        <td style = "background-color:<%= traffic_light.colour %>">
        <%= traffic_light.id.to_s + ": " + traffic_light.colour %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Back to main menu", "/" %>
</p>

app/views/junctions/new.html.erb
<h1>New Junction</h1>

<%= form_for :junction, url: junctions_path do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
    <%= if @junction; @junction.errors.full_messages end %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to junctions", junctions_path %>

app/views/junctions/show.html.erb
<h1>Here is your junction</h1>

<p>
  <b>Name</b><br />
  <%= @junction.name %>
</p>
<p>
  <b>ID</b><br />
  <%= @junction.id %>
</p>

<%= link_to "Back to junctions", junctions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrafficLights</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/traffic_lights/edit.html.erb
<h1>Editing traffic light</h1>

<%= form_for :traffic_light, url: traffic_light_path(@traffic_light), method: :patch do |f| %>
  <p>
    <%= f.label :junction %><br />
    <%= f.select :junction_id, options_for_select(Junction.all.map { |j| [j.name, j.id] }, @traffic_light.junction_id) %>
  </p>
  <p>
    <%= f.label :colour %><br />
    <%= f.select :colour, options_for_select(["Red", "Yellow", "Green"], @traffic_light.colour) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", traffic_lights_path %>

app/views/traffic_lights/index.html.erb
<style = "text/css">
  td {
    padding: 5px;
  }
</style>

<h1>Traffic Lights:</h1>




<table>
  <tr>
    <td><b>ID</b></td>
    <td><b>Colour</b></td>
    <td><b>Junction</b></td>
    <td><b>Junction ID</b></td>
    <td><b>Update</b></td>
    <td><b>Delete</b></td>
  </tr>
  <% @traffic_lights.each do |traffic_light| %>
    <tr>
      <td><%= traffic_light.id %></td>
      <td style = "background-color: <%= traffic_light.colour %>"><%= traffic_light.colour %></td>
      <td><%= Junction.find(traffic_light.junction_id).name %></td>
      <td><%= traffic_light.junction_id %></td>
      <td><%= link_to "Update", edit_traffic_light_path(traffic_light.id) %></td>
      <td><%= link_to "Delete", traffic_light_path(traffic_light.id), :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Back to main menu", "/" %>
</p>

app/views/traffic_lights/new.html.erb
<h1>Traffic Light</h1>

<%= form_for :traffic_light, url: traffic_lights_path do |f| %>
  <p>
    <%= f.hidden_field :junction_id, :value => params[:junction_id] %>
  </p>
  <p>
    <%= f.label :colour %><br />
    <%= f.select :colour, options_for_select(["Red", "Yellow", "Green"]) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", traffic_lights_path %>

app/views/traffic_lights/show.html.erb
<h1>Here is your traffic light:</h1>

<p>
  <b>ID</b><br />
  <%= @traffic_light.id %>
</p>
<p>
  <b>Junction name</b><br />
  <%= Junction.find(@traffic_light.junction_id).name %>
</p>
<p>
  <b>Junction ID</b><br />
  <%= @traffic_light.junction_id %>
</p>
<p>
  <b>Colour</b><br />
  <%= @traffic_light.colour %>
</p>

 <%= link_to "Back to all traffic lights", traffic_lights_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to "Junctions", controller: "junctions" %><br />
<%= link_to "Traffic Lights", controller: "traffic_lights" %>